# Generated by Django 3.2.4 on 2021-06-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.BooleanField()),
                ('birth_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=63)),
                ('season', models.CharField(max_length=63)),
                ('year', models.SmallIntegerField()),
                ('city', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=63)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('noc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.noc')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=63)),
                ('sport', models.CharField(max_length=63)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.games')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteEventStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('medal', models.SmallIntegerField()),
                ('atlhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
